server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      min-idle: 5
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/wind_gone?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
