server:
  port: 8001

spring:
  application:
    name: cloud-customer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/seata_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
