server:
  port: 8801

spring:
  application:
    name: cloud-stream-producer-kafka
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111  #Nacos服务注册中心地址,使用nginx代理地址
    #消息驱动
    stream:
      kafka:
        binder:
          brokers: localhost:9092,localhost:9094  #kafka集群
      bindings:
        kafka_out:
          destination: aa
          content-type: text/plain




#端点暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'





