server:
  port: 1234

spring:
  mvc:
    static-path-pattern: /**       #满足才会执行非controller请求,默认即/**
#  resources:
#    static-locations:            #静态资源位置,去哪里找静态资源[配合freemaker使用,类似于nginx)
#      - classpath:/templates
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/wind_gone?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 5  #初始化大小
      min-idle: 5  #最小
      max-active: 5 #最大
      test-while-idle: false  #关闭druid空闲检测
  #模板引擎
  freemarker:
    template-loader-path:
      - classpath:/templates/
    suffix: .html   #模板文件后缀名
  redis:
    host: 127.0.0.1
    port: 6380


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志