server:
  port: 1234

spring:
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - classpath:/static/sys
      - classpath:/templates
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/wind_gone?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 5  #初始化大小
      min-idle: 5  #最小
      max-active: 5 #最大
      test-while-idle: false  #关闭druid空闲检测
  #模板引擎
  freemarker:
    template-loader-path:
      - classpath:/templates/
      - classpath:/static/
    suffix: .html   #模板文件后缀名



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

